name: Supabase Daily Backup

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch: 

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump Database
        run: |
          # Menggunakan port 6543 dan menonaktifkan pemeriksaan SSL sertifikat untuk kelancaran dump
          pg_dump "${{ secrets.DB_URL }}" > backup.sql
        env:
          PGSSLMODE: 'disable' # Membantu menghindari error handshake SSL pada port pooling
